resolver: lts-3.19
compiler: ghc-7.10.3

packages:
- '.'
#smtlib2 1.0
- location:
    git: https://github.com/hguenther/smtlib2.git
    commit: c0d0ad3a72668efc1cc59c3641916e1a7e502e30
  subdirs:
    - '.'
    - backends/debug
    - backends/pipe
    - backends/timing
    - extras/emulated-modulus
  extra-dep: true
#bindings-llvm
- location:
    git: https://github.com/simonjantsch/bindings-llvm.git
    commit: bb17f7c31bef683feda4c777378cd25602cc5815
  extra-dep: true

extra-deps:
- atto-lisp-0.2.2.2
- data-fix-0.0.1
- pqueue-1.3.1
- dependent-map-0.2.1.0
- dependent-sum-0.3.2.1
